version: '3'
services:
  backend-java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prac6_java
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql
    hostname: mysql
    container_name: prac6_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prac6DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"